version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: todo-list-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9090:9090"

volumes:
  postgres-data:
    driver: local
